wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.0
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700866767.302812
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 1
      - 19
      - 23
      4: 3.10.6
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
